### ISSUE TITLE
CorrectBisectorDirection Error on geometry with hole

### ISSUE THREAD

**Issue by wlievens** [StrandedKitty/straight-skeleton#4]
I'm getting the following exception when feeding a polygon with one hole:

```
Error
    at Function.CorrectBisectorDirection (D:\Workspaces\griffin\griffin-renderer\node_modules\straight-skeleton\src\lib\SkeletonBuilder.ts:260:10)
    at Function.MultiSplitEvent (D:\Workspaces\griffin\griffin-renderer\node_modules\straight-skeleton\src\lib\SkeletonBuilder.ts:221:9)
    at Function.Build (D:\Workspaces\griffin\griffin-renderer\node_modules\straight-skeleton\src\lib\SkeletonBuilder.ts:103:11)
    at Function.BuildFromGeoJSON (D:\Workspaces\griffin\griffin-renderer\node_modules\straight-skeleton\src\lib\SkeletonBuilder.ts:45:27)
```

Below is an image of the geometry.

The Live Demo gave me the impression that holes are robustly supported so I figured I'd report this.

This is the exact input to `SkeletonBuilder.BuildFromGeoJSON()`:

`const polygon = [[[[-9,-6],[-8.9997727,-6.0843146],[-8.9990909,-6.1685687],[-8.9979546,-6.2527625],[-8.9963637,-6.336895800000001],[-8.9943183,-6.4209687],[-8.9918184,-6.504981300000001],[-8.9888639,-6.588933399999999],[-8.985454899999999,-6.672825100000001],[-8.9815914,-6.7566563],[-8.9772733,-6.8404272],[-8.9725007,-6.9241377],[-8.9672736,-7.007787700000001],[-8.9615919,-7.091377400000001],[-8.9554557,-7.1749066],[-8.9488649,-7.2583754],[-8.9418197,-7.341783800000001],[-8.9343198,-7.4251319],[-8.926365500000001,-7.5084194],[-8.9179566,-7.591646600000001],[-8.9090932,-7.6748134],[-8.8997753,-7.7579198],[-8.8900028,-7.8409657],[-8.8797758,-7.923951300000001],[-8.8690942,-8.006876400000001],[-8.8579581,-8.0897411],[-8.8463675,-8.1725454],[-8.8343224,-8.2552893],[-8.8218227,-8.337972800000001],[-8.8088685,-8.4205959],[-8.7954597,-8.503158599999999],[-8.7815964,-8.5856608],[-8.767278600000001,-8.6681027],[-8.7525062,-8.7504841],[-8.7372794,-8.832805200000001],[-8.721597899999999,-8.915065799999999],[-8.705462,-8.997266],[-8.6888715,-9.0794058],[-8.6718265,-9.1614852],[-8.6543269,-9.2435042],[-8.6363728,-9.325462700000001],[-8.617964200000001,-9.407360899999999],[-8.599101000000001,-9.4891986],[-8.5797833,-9.570976],[-8.5600111,-9.6526929],[-8.539784299999999,-9.7343494],[-8.5191031,-9.8159455],[-8.4979672,-9.897481200000001],[-8.4763769,-9.9789565],[-8.454331999999999,-10.060371400000001],[-8.4318325,-10.1417258],[-8.4088786,-10.2230199],[-8.3854701,-10.304253600000001],[-8.361607,-10.3854268],[-8.3372895,-10.4665396],[-8.3125174,-10.547592000000002],[-8.2872907,-10.628584],[-8.2616096,-10.7095156],[-8.2354739,-10.7903868],[-8.2088836,-10.8711976],[-8.1818388,-10.951948000000002],[-8.154339499999999,-11.0326379],[-8.1263857,-11.1132675],[-8.0979773,-11.193836600000001],[-8.0691144,-11.2743453],[-8.039797,-11.3547936],[-8.010025,-11.435181499999999],[-7.9797985,-11.515509000000002],[-7.9491174,-11.5957761],[-7.9179819,-11.6759828],[-7.8863918,-11.756129000000001],[-7.8543471,-11.8362149],[-7.821847900000001,-11.9162403],[-7.7888942000000005,-11.996205400000001],[-7.755485999999999,-12.07611],[-7.7216232,-12.1559542],[-7.6873059,-12.235738],[-7.652534,-12.3154614],[-7.6173076,-12.3951244],[-7.5816267,-12.4747269],[-7.545491299999999,-12.554269099999999],[-7.5089013,-12.6337509],[-7.471856799999999,-12.7131722],[-7.4343577,-12.7925331],[-7.3964041,-12.8718336],[-7.357996,-12.951073800000001],[-7.3191334,-13.0302535],[-7.279816199999999,-13.109372700000002],[-7.2400443999999995,-13.1884316],[-7.1998182,-13.267430099999999],[-7.1591374000000005,-13.3463681],[-7.1180021,-13.425245799999999],[-7.0764122,-13.504063],[-7.0343678,-13.582819899999999],[-6.9918689,-13.6615163],[-6.948915400000001,-13.7401523],[-6.905507399999999,-13.818727899999999],[-6.861644900000001,-13.8972431],[-6.8173278,-13.9756978],[-6.7725562,-14.0540922],[-6.7273301000000005,-14.132426200000001],[-6.681649500000001,-14.210699700000001],[-6.6355143000000005,-14.2889128],[-6.588924500000001,-14.367065599999998],[-6.5418803,-14.445157899999998],[-6.4943815,-14.5231898],[-6.4464281,-14.6011613],[-6.3980203,-14.679072399999999],[-6.3491578,-14.756923],[-6.2998408999999995,-14.834713299999999],[-6.2500694,-14.912443199999998],[-6.1998434,-14.990112600000002],[-6.1491629,-15.067721599999999],[-6.0980278000000006,-15.1452703],[-6.046438200000001,-15.222758500000001],[-5.9943941,-15.3001863],[-5.9418954,-15.3775537],[-5.8889422,-15.454860700000001],[-5.8355345000000005,-15.532107199999999],[-5.7816722,-15.609293399999999],[-5.7273554,-15.686419100000002],[-5.6725840000000005,-15.763484499999999],[-5.617358100000001,-15.8404894],[-5.561677700000001,-15.9174339],[-5.505542800000001,-15.994318],[-5.4489532999999994,-16.0711418],[-5.3919093,-16.147905],[-5.3344107,-16.2246079],[-5.2764577,-16.301250399999997],[-5.21805,-16.3778325],[-5.1591879,-16.4543541],[-5.0998712,-16.5308153],[-5.0401,-16.6072162],[-4.9798742,-16.6835566],[-4.919194,-16.7598366],[-4.8580591,-16.836056199999998],[-4.7964698,-16.9122154],[-4.734425900000001,-16.9883142],[-4.6719275,-17.0643525],[-4.6089745,-17.1403305],[-4.545567,-17.216248],[-4.481705,-17.2921052],[-4.4173884,-17.3679019],[-4.3526174,-17.4436382],[-4.2873917,-17.5193141],[-4.2217116,-17.5949296],[-4.1555769,-17.6704847],[-4.0889877,-17.7459794],[-4.0219439,-17.8214136],[-3.9544455999999997,-17.8967875],[-3.8864928,-17.972101],[-3.8180853999999997,-18.047354],[-3.7492235000000003,-18.1225466],[-3.6799071,-18.197678800000002],[-3.6101361,-18.272750600000002],[-3.5399106,-18.347762],[-3.4692305999999995,-18.422712999999998],[-3.398096,-18.4976036],[-3.3265069,-18.5724337],[-3.2544633,-18.6472035],[-3.1819650999999998,-18.7219128],[-3.1090124,-18.7965618],[-3.0356052,-18.8711503],[-2.9617434,-18.945678400000002],[-2.8874271,-19.0201461],[-2.8126562,-19.0945534],[-2.7374309,-19.1689003],[-2.661751,-19.2431868],[-2.5856165,-19.3174128],[-2.5090275,-19.3915785],[-2.431984,-19.4656837],[-2.354486,-19.5397285],[-2.2765334,-19.613713],[-2.1981262999999998,-19.687637],[-2.1192647,-19.7615006],[-2.0399485,-19.835303800000002],[-1.9601778,-19.909046500000002],[-1.8799525,-19.982728899999998],[-1.7992727,-20.056350899999998],[-1.7181384,-20.1299124],[-1.6365496000000002,-20.2034136],[-1.5545062,-20.2768543],[-1.4720083,-20.3502346],[-1.3890558,-20.4235545],[-1.3056488000000002,-20.496814],[-1.2217873,-20.5700131],[-1.1374713,-20.6431518],[-1.0527007,-20.7162301],[-0.9674756000000001,-20.7892479],[-0.8817959000000001,-20.8622054],[-0.7956617,-20.9351024],[-0.7090730000000001,-21.007939],[-0.6220297,-21.0807152],[-0.534532,-21.153430999999998],[-0.4465796,-21.2260864],[-0.3581728,-21.2986814],[-0.26931140000000003,-21.371216],[-0.1799955,-21.443690200000002],[-0.090225,-21.5161039],[0,-21.5884573],[0.090225,-21.5161039],[0.1799955,-21.443690200000002],[0.26931140000000003,-21.371216],[0.3581728,-21.2986814],[0.4465796,-21.2260864],[0.534532,-21.153430999999998],[0.6220297,-21.0807152],[0.7090730000000001,-21.007939],[0.7956617,-20.9351024],[0.8817959000000001,-20.8622054],[0.9674756000000001,-20.7892479],[1.0527007,-20.7162301],[1.1374713,-20.6431518],[1.2217873,-20.5700131],[1.3056488000000002,-20.496814],[1.3890558,-20.4235545],[1.4720083,-20.3502346],[1.5545062,-20.2768543],[1.6365496000000002,-20.2034136],[1.7181384,-20.1299124],[1.7992727,-20.056350899999998],[1.8799525,-19.982728899999998],[1.9601778,-19.909046500000002],[2.0399485,-19.835303800000002],[2.1192647,-19.7615006],[2.1981262999999998,-19.687637],[2.2765334,-19.613713],[2.354486,-19.5397285],[2.431984,-19.4656837],[2.5090275,-19.3915785],[2.5856165,-19.3174128],[2.661751,-19.2431868],[2.7374309,-19.1689003],[2.8126562,-19.0945534],[2.8874271,-19.0201461],[2.9617434,-18.945678400000002],[3.0356052,-18.8711503],[3.1090124,-18.7965618],[3.1819650999999998,-18.7219128],[3.2544633,-18.6472035],[3.3265069,-18.5724337],[3.398096,-18.4976036],[3.4692305999999995,-18.422712999999998],[3.5399106,-18.347762],[3.6101361,-18.272750600000002],[3.6799071,-18.197678800000002],[3.7492235000000003,-18.1225466],[3.8180853999999997,-18.047354],[3.8864928,-17.972101],[3.9544455999999997,-17.8967875],[4.0219439,-17.8214136],[4.0889877,-17.7459794],[4.1555769,-17.6704847],[4.2217116,-17.5949296],[4.2873917,-17.5193141],[4.3526174,-17.4436382],[4.4173884,-17.3679019],[4.481705,-17.2921052],[4.545567,-17.216248],[4.6089745,-17.1403305],[4.6719275,-17.0643525],[4.734425900000001,-16.9883142],[4.7964698,-16.9122154],[4.8580591,-16.836056199999998],[4.919194,-16.7598366],[4.9798742,-16.6835566],[5.0401,-16.6072162],[5.0998712,-16.5308153],[5.1591879,-16.4543541],[5.21805,-16.3778325],[5.2764577,-16.301250399999997],[5.3344107,-16.2246079],[5.3919093,-16.147905],[5.4489532999999994,-16.0711418],[5.505542800000001,-15.994318],[5.561677700000001,-15.9174339],[5.617358100000001,-15.8404894],[5.6725840000000005,-15.763484499999999],[5.7273554,-15.686419100000002],[5.7816722,-15.609293399999999],[5.8355345000000005,-15.532107199999999],[5.8889422,-15.454860700000001],[5.9418954,-15.3775537],[5.9943941,-15.3001863],[6.046438200000001,-15.222758500000001],[6.0980278000000006,-15.1452703],[6.1491629,-15.067721599999999],[6.1998434,-14.990112600000002],[6.2500694,-14.912443199999998],[6.2998408999999995,-14.834713299999999],[6.3491578,-14.756923],[6.3980203,-14.679072399999999],[6.4464281,-14.6011613],[6.4943815,-14.5231898],[6.5418803,-14.445157899999998],[6.588924500000001,-14.367065599999998],[6.6355143000000005,-14.2889128],[6.681649500000001,-14.210699700000001],[6.7273301000000005,-14.132426200000001],[6.7725562,-14.0540922],[6.8173278,-13.9756978],[6.861644900000001,-13.8972431],[6.905507399999999,-13.818727899999999],[6.948915400000001,-13.7401523],[6.9918689,-13.6615163],[7.0343678,-13.582819899999999],[7.0764122,-13.504063],[7.1180021,-13.425245799999999],[7.1591374000000005,-13.3463681],[7.1998182,-13.267430099999999],[7.2400443999999995,-13.1884316],[7.279816199999999,-13.109372700000002],[7.3191334,-13.0302535],[7.357996,-12.951073800000001],[7.3964041,-12.8718336],[7.4343577,-12.7925331],[7.471856799999999,-12.7131722],[7.5089013,-12.6337509],[7.545491299999999,-12.554269099999999],[7.5816267,-12.4747269],[7.6173076,-12.3951244],[7.652534,-12.3154614],[7.6873059,-12.235738],[7.7216232,-12.1559542],[7.755485999999999,-12.07611],[7.7888942000000005,-11.996205400000001],[7.821847900000001,-11.9162403],[7.8543471,-11.8362149],[7.8863918,-11.756129000000001],[7.9179819,-11.6759828],[7.9491174,-11.5957761],[7.9797985,-11.515509000000002],[8.010025,-11.435181499999999],[8.039797,-11.3547936],[8.0691144,-11.2743453],[8.0979773,-11.193836600000001],[8.1263857,-11.1132675],[8.154339499999999,-11.0326379],[8.1818388,-10.951948000000002],[8.2088836,-10.8711976],[8.2354739,-10.7903868],[8.2616096,-10.7095156],[8.2872907,-10.628584],[8.3125174,-10.547592000000002],[8.3372895,-10.4665396],[8.361607,-10.3854268],[8.3854701,-10.304253600000001],[8.4088786,-10.2230199],[8.4318325,-10.1417258],[8.454331999999999,-10.060371400000001],[8.4763769,-9.9789565],[8.4979672,-9.897481200000001],[8.5191031,-9.8159455],[8.539784299999999,-9.7343494],[8.5600111,-9.6526929],[8.5797833,-9.570976],[8.599101000000001,-9.4891986],[8.617964200000001,-9.407360899999999],[8.6363728,-9.325462700000001],[8.6543269,-9.2435042],[8.6718265,-9.1614852],[8.6888715,-9.0794058],[8.705462,-8.997266],[8.721597899999999,-8.915065799999999],[8.7372794,-8.832805200000001],[8.7525062,-8.7504841],[8.767278600000001,-8.6681027],[8.7815964,-8.5856608],[8.7954597,-8.503158599999999],[8.8088685,-8.4205959],[8.8218227,-8.337972800000001],[8.8343224,-8.2552893],[8.8463675,-8.1725454],[8.8579581,-8.0897411],[8.8690942,-8.006876400000001],[8.8797758,-7.923951300000001],[8.8900028,-7.8409657],[8.8997753,-7.7579198],[8.9090932,-7.6748134],[8.9179566,-7.591646600000001],[8.926365500000001,-7.5084194],[8.9343198,-7.4251319],[8.9418197,-7.341783800000001],[8.9488649,-7.2583754],[8.9554557,-7.1749066],[8.9615919,-7.091377400000001],[8.9672736,-7.007787700000001],[8.9725007,-6.9241377],[8.9772733,-6.8404272],[8.9815914,-6.7566563],[8.985454899999999,-6.672825100000001],[8.9888639,-6.588933399999999],[8.9918184,-6.504981300000001],[8.9943183,-6.4209687],[8.9963637,-6.336895800000001],[8.9979546,-6.2527625],[8.9990909,-6.1685687],[8.9997727,-6.0843146],[9,-6],[9,0],[-9,0]],[[-6.4285714,-5.9965339],[-6.4285714,-2.5714286],[6.4285714,-2.5714286],[6.4285714,-5.9965339],[6.4283722,-6.070444500000001],[6.4278027,-6.1408139],[6.4268541,-6.2111039],[6.4255264,-6.2813171],[6.423819999999999,-6.3514563],[6.4217352,-6.4215198000000004],[6.419271999999999,-6.491510099999999],[6.4164308,-6.5614300000000005],[6.4132117,-6.6312777],[6.4096149,-6.7010561],[6.4056404,-6.770767800000001],[6.4012886,-6.8404110000000005],[6.3965593,-6.9099886],[6.3914527,-6.979501600000001],[6.3859688000000006,-7.0489531],[6.3801078,-7.1183412],[6.3738695000000005,-7.187668599999999],[6.367254,-7.2569379000000005],[6.3602613,-7.326148],[6.3528913,-7.3953026],[6.3451441,-7.4643999999999995],[6.3370194,-7.5334430999999995],[6.3285171,-7.6024333],[6.3196372,-7.671371499999999],[6.3103792,-7.740260800000001],[6.300743300000001,-7.809100900000001],[6.2907294,-7.8778915000000005],[6.280336999999999,-7.9466354],[6.269566,-8.015333799999999],[6.2584161,-8.0839877],[6.2468867,-8.1526002],[6.2349782000000005,-8.2211696],[6.2226896,-8.2896998],[6.2100212,-8.3581893],[6.1969722,-8.4266404],[6.1835422,-8.4950563],[6.1697311,-8.5634349],[6.1555385,-8.631779100000001],[6.1409637,-8.7000896],[6.126006100000001,-8.7683696],[6.1106658,-8.8366172],[6.0949419,-8.9048348],[6.0788338,-8.9730252],[6.0623416,-9.041186100000001],[6.045463900000001,-9.1093223],[6.028201,-9.1774316],[6.0105518,-9.245516499999999],[5.9925157,-9.3135796],[5.974093,-9.3816173],[5.9552814000000005,-9.4496369],[5.9360812,-9.5176368],[5.9164927,-9.585614],[5.8965135,-9.6535757],[5.8761437,-9.7215206],[5.8553834,-9.7894465],[5.8342303,-9.85736],[5.8126847,-9.9252591],[5.7907465,-9.993141999999999],[5.7684137,-10.0610138],[5.7456858,-10.1288749],[5.7225621,-10.1967254],[5.6990426,-10.2645648],[5.6751261,-10.3323945],[5.650811,-10.400217699999999],[5.6260978,-10.468032000000001],[5.6009850000000005,-10.535839500000002],[5.5754719,-10.6036411],[5.5495571,-10.6714386],[5.5232407,-10.7392311],[5.4965223,-10.8070175],[5.4693997,-10.8748021],[5.4418722,-10.9425853],[5.4139394,-11.0103667],[5.3856013,-11.0781449],[5.3568559,-11.1459229],[5.3277026,-11.2137008],[5.2981407,-11.2814792],[5.2681688,-11.3492592],[5.2377864,-11.4170411],[5.2069928999999995,-11.4848245],[5.1757878,-11.5526092],[5.144169600000001,-11.6203967],[5.1121372,-11.688188199999999],[5.079689200000001,-11.755985299999999],[5.0468259,-11.823786],[5.0135471,-11.891589],[4.979851,-11.9593968],[4.945735,-12.0272129],[4.9112007,-12.0950335],[4.876246500000001,-12.1628594],[4.8408715,-12.2306916],[4.8050747000000005,-12.2985303],[4.7688547,-12.366377],[4.7322122,-12.4342289],[4.6951451,-12.5020886],[4.6576521,-12.569956900000001],[4.6197342,-12.6378312],[4.581389000000001,-12.7057138],[4.542615199999999,-12.7736062],[4.5034135,-12.8415055],[4.4637832,-12.909411900000002],[4.423722499999999,-12.977326900000001],[4.3832299,-13.0452518],[4.342306,-13.1131846],[4.300950299999999,-13.181124599999999],[4.2591598,-13.2490752],[4.2169362999999995,-13.3170329],[4.1742772,-13.384999800000001],[4.1311814,-13.4529772],[4.0876505000000005,-13.520961],[4.0436816,-13.5889544],[3.9992745000000003,-13.656956700000002],[3.9544289,-13.7249671],[3.9091436,-13.7929862],[3.8634181,-13.861013499999999],[3.8172516000000005,-13.929049200000001],[3.7706430999999996,-13.9970934],[3.7235924,-14.0651455],[3.6760985,-14.1332057],[3.6281605999999997,-14.2012737],[3.5797782,-14.269349599999998],[3.5309503,-14.3374333],[3.4816761,-14.4055251],[3.4319556,-14.473624],[3.3817886,-14.5417288],[3.3311738,-14.6098403],[3.2801089,-14.6779607],[3.2285959999999996,-14.7460862],[3.1766337,-14.8142173],[3.1242205,-14.882355200000001],[3.0713559000000004,-14.950499399999998],[3.0180403,-15.0186486],[2.9642724,-15.0868033],[2.9100520000000003,-15.1549628],[2.8553781,-15.2231271],[2.8002499000000003,-15.291296800000001],[2.7446684,-15.3594692],[2.6886315,-15.427646199999998],[2.632139,-15.495827],[2.57519,-15.564011800000001],[2.5177852,-15.6321989],[2.4599232000000004,-15.7003889],[2.4016040000000003,-15.7685812],[2.3428266,-15.8367756],[2.2835902999999997,-15.9049725],[2.2238957,-15.973170199999998],[2.1637424,-16.0413684],[2.1031286,-16.1095679],[2.0420533,-16.1777692],[1.9805191999999998,-16.2459688],[1.9185240000000001,-16.314167899999998],[1.8560661,-16.3823678],[1.7931469,-16.450566000000002],[1.7297653999999998,-16.518763],[1.6659205000000001,-16.5869589],[1.6016132,-16.655151999999998],[1.5368431,-16.7233422],[1.4716079,-16.7915307],[1.4059092,-16.8597155],[1.3397459,-16.9278967],[1.2731172,-16.9960747],[1.2060245,-17.064247],[1.1384657,-17.1324153],[1.070441,-17.200578500000002],[1.0019496,-17.2687369],[0.9329917999999999,-17.3368894],[0.8635691,-17.405034],[0.7936781,-17.473173],[0.7233191,-17.5413057],[0.6524933,-17.6094304],[0.581199,-17.6775479],[0.5094372,-17.745656699999998],[0.4372071,-17.813756899999998],[0.3645085,-17.8818482],[0.29134150000000003,-17.9499295],[0.21770489999999998,-18.0180017],[0.1435983,-18.086064399999998],[0.0690229,-18.154116],[0,-18.216696600000002],[-0.0690229,-18.154116],[-0.1435983,-18.086064399999998],[-0.21770489999999998,-18.0180017],[-0.29134150000000003,-17.9499295],[-0.3645085,-17.8818482],[-0.4372071,-17.813756899999998],[-0.5094372,-17.745656699999998],[-0.581199,-17.6775479],[-0.6524933,-17.6094304],[-0.7233191,-17.5413057],[-0.7936781,-17.473173],[-0.8635691,-17.405034],[-0.9329917999999999,-17.3368894],[-1.0019496,-17.2687369],[-1.070441,-17.200578500000002],[-1.1384657,-17.1324153],[-1.2060245,-17.064247],[-1.2731172,-16.9960747],[-1.3397459,-16.9278967],[-1.4059092,-16.8597155],[-1.4716079,-16.7915307],[-1.5368431,-16.7233422],[-1.6016132,-16.655151999999998],[-1.6659205000000001,-16.5869589],[-1.7297653999999998,-16.518763],[-1.7931469,-16.450566000000002],[-1.8560661,-16.3823678],[-1.9185240000000001,-16.314167899999998],[-1.9805191999999998,-16.2459688],[-2.0420533,-16.1777692],[-2.1031286,-16.1095679],[-2.1637424,-16.0413684],[-2.2238957,-15.973170199999998],[-2.2835902999999997,-15.9049725],[-2.3428266,-15.8367756],[-2.4016040000000003,-15.7685812],[-2.4599232000000004,-15.7003889],[-2.5177852,-15.6321989],[-2.57519,-15.564011800000001],[-2.632139,-15.495827],[-2.6886315,-15.427646199999998],[-2.7446684,-15.3594692],[-2.8002499000000003,-15.291296800000001],[-2.8553781,-15.2231271],[-2.9100520000000003,-15.1549628],[-2.9642724,-15.0868033],[-3.0180403,-15.0186486],[-3.0713559000000004,-14.950499399999998],[-3.1242205,-14.882355200000001],[-3.1766337,-14.8142173],[-3.2285959999999996,-14.7460862],[-3.2801089,-14.6779607],[-3.3311738,-14.6098403],[-3.3817886,-14.5417288],[-3.4319556,-14.473624],[-3.4816761,-14.4055251],[-3.5309503,-14.3374333],[-3.5797782,-14.269349599999998],[-3.6281605999999997,-14.2012737],[-3.6760985,-14.1332057],[-3.7235924,-14.0651455],[-3.7706430999999996,-13.9970934],[-3.8172516000000005,-13.929049200000001],[-3.8634181,-13.861013499999999],[-3.9091436,-13.7929862],[-3.9544289,-13.7249671],[-3.9992745000000003,-13.656956700000002],[-4.0436816,-13.5889544],[-4.0876505000000005,-13.520961],[-4.1311814,-13.4529772],[-4.1742772,-13.384999800000001],[-4.2169362999999995,-13.3170329],[-4.2591598,-13.2490752],[-4.300950299999999,-13.181124599999999],[-4.342306,-13.1131846],[-4.3832299,-13.0452518],[-4.423722499999999,-12.977326900000001],[-4.4637832,-12.909411900000002],[-4.5034135,-12.8415055],[-4.542615199999999,-12.7736062],[-4.581389000000001,-12.7057138],[-4.6197342,-12.6378312],[-4.6576521,-12.569956900000001],[-4.6951451,-12.5020886],[-4.7322122,-12.4342289],[-4.7688547,-12.366377],[-4.8050747000000005,-12.2985303],[-4.8408715,-12.2306916],[-4.876246500000001,-12.1628594],[-4.9112007,-12.0950335],[-4.945735,-12.0272129],[-4.979851,-11.9593968],[-5.0135471,-11.891589],[-5.0468259,-11.823786],[-5.079689200000001,-11.755985299999999],[-5.1121372,-11.688188199999999],[-5.144169600000001,-11.6203967],[-5.1757878,-11.5526092],[-5.2069928999999995,-11.4848245],[-5.2377864,-11.4170411],[-5.2681688,-11.3492592],[-5.2981407,-11.2814792],[-5.3277026,-11.2137008],[-5.3568559,-11.1459229],[-5.3856013,-11.0781449],[-5.4139394,-11.0103667],[-5.4418722,-10.9425853],[-5.4693997,-10.8748021],[-5.4965223,-10.8070175],[-5.5232407,-10.7392311],[-5.5495571,-10.6714386],[-5.5754719,-10.6036411],[-5.6009850000000005,-10.535839500000002],[-5.6260978,-10.468032000000001],[-5.650811,-10.400217699999999],[-5.6751261,-10.3323945],[-5.6990426,-10.2645648],[-5.7225621,-10.1967254],[-5.7456858,-10.1288749],[-5.7684137,-10.0610138],[-5.7907465,-9.993141999999999],[-5.8126847,-9.9252591],[-5.8342303,-9.85736],[-5.8553834,-9.7894465],[-5.8761437,-9.7215206],[-5.8965135,-9.6535757],[-5.9164927,-9.585614],[-5.9360812,-9.5176368],[-5.9552814000000005,-9.4496369],[-5.974093,-9.3816173],[-5.9925157,-9.3135796],[-6.0105518,-9.245516499999999],[-6.028201,-9.1774316],[-6.045463900000001,-9.1093223],[-6.0623416,-9.041186100000001],[-6.0788338,-8.9730252],[-6.0949419,-8.9048348],[-6.1106658,-8.8366172],[-6.126006100000001,-8.7683696],[-6.1409637,-8.7000896],[-6.1555385,-8.631779100000001],[-6.1697311,-8.5634349],[-6.1835422,-8.4950563],[-6.1969722,-8.4266404],[-6.2100212,-8.3581893],[-6.2226896,-8.2896998],[-6.2349782000000005,-8.2211696],[-6.2468867,-8.1526002],[-6.2584161,-8.0839877],[-6.269566,-8.015333799999999],[-6.280336999999999,-7.9466354],[-6.2907294,-7.8778915000000005],[-6.300743300000001,-7.809100900000001],[-6.3103792,-7.740260800000001],[-6.3196372,-7.671371499999999],[-6.3285171,-7.6024333],[-6.3370194,-7.5334430999999995],[-6.3451441,-7.4643999999999995],[-6.3528913,-7.3953026],[-6.3602613,-7.326148],[-6.367254,-7.2569379000000005],[-6.3738695000000005,-7.187668599999999],[-6.3801078,-7.1183412],[-6.3859688000000006,-7.0489531],[-6.3914527,-6.979501600000001],[-6.3965593,-6.9099886],[-6.4012886,-6.8404110000000005],[-6.4056404,-6.770767800000001],[-6.4096149,-6.7010561],[-6.4132117,-6.6312777],[-6.4164308,-6.5614300000000005],[-6.419271999999999,-6.491510099999999],[-6.4217352,-6.4215198000000004],[-6.423819999999999,-6.3514563],[-6.4255264,-6.2813171],[-6.4268541,-6.2111039],[-6.4278027,-6.1408139],[-6.4283722,-6.070444500000001]]]];
`

![image](https://user-images.githubusercontent.com/1073326/225280577-3cba741a-51ae-452f-948c-8db2ebb49b10.png)

**Comment by wlievens** [comment]
A large portion of the shape is an interpolated bezier, so there are many points. Simplifying the geometry (automatically) is certainly acceptable as I'm only interested in an approximate straight skeleton, so I'll give that a try too.
